# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 12:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_detector', '0003_auto_20180309_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('neutral', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contempt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disgust', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anger', models.DecimalField(decimal_places=2, max_digits=5)),
                ('surprise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fear', models.DecimalField(decimal_places=2, max_digits=5)),
                ('happiness', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='face_detector.Emotion')),
            ],
        ),
        migrations.CreateModel(
            name='FaceOnGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='face_detector.Emotion')),
            ],
        ),
        migrations.CreateModel(
            name='FramePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomePagePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='photos',
            name='user',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.AddField(
            model_name='framephoto',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_detector.Video'),
        ),
        migrations.AddField(
            model_name='faceongroup',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='face_detector.Gender'),
        ),
        migrations.AddField(
            model_name='faceongroup',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_detector.GroupPhoto'),
        ),
        migrations.AddField(
            model_name='face',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_detector.FramePhoto'),
        ),
        migrations.AddField(
            model_name='face',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='face_detector.Gender'),
        ),
        migrations.AddField(
            model_name='diaryphoto',
            name='emotions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='face_detector.Emotion'),
        ),
        migrations.AddField(
            model_name='diaryphoto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
